config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'about', to: 'pages#about'

  get 'wishlist', to: 'pages#wishlist'

  post 'wishlist', to: 'pages#destroy'

  resources :books, only: [ :index, :show, :new, :create ]
end

app/views/pages/about.html.erb
<div class="container">
  <h1 style="margin-top:10px">Welcome to BookAdvisor!</h1>

  <p>BookAdvisor is a bookstore metesearch.</p>

  <p>We believe that bookstores are essential to a healthy culture. They’re where authors can connect with readers, where we discover new writers, where children get hooked on the thrill of reading that can last a lifetime. They’re also anchors for our downtowns and communities.</p>

  <p>As more and more people buy their books online, we wanted to create an easy, convenient way for you to get your books and support bookstores at the same time.</p>

  <h2>Founders:</h2>

  <div class="container" style="margin-bottom: 20px;">
    <div class="cards" style="justify-content: space-between;">
      <div class="card-product" style="width: 300px;">
        <img src="https://media-exp1.licdn.com/dms/image/C4E03AQFSPuxa6ibV-A/profile-displayphoto-shrink_200_200/0/1576292896774?e=1623283200&v=beta&t=skxQk-S6FE2wl_8GdEvmccZFM-A2FpVmWs49UbxkgG0" />
        <div class="card-product-infos">
          <h2>Tomás Agnese</h2>
          <a href="https://www.linkedin.com/in/tomasagnese/" target="_blank">
            <i class="fab fa-linkedin fa-lg"></i>
          </a>
          <a href="https://github.com/tomag1985" target="_blank">
            <i class="fab fa-github fa-lg"></i>
          </a>
        </div>
      </div>

      <div class="card-product" style="width: 300px;">
        <img src="https://media-exp1.licdn.com/dms/image/C4E03AQGdFmMtA_AFEQ/profile-displayphoto-shrink_200_200/0/1585506828516?e=1624492800&v=beta&t=N_EDwrDHDCDel-7HeqrvDwwIzCaJYE79E4s5cOO2niQ" />
        <div class="card-product-infos">
          <h2>Rocío Picaza</h2>
          <a href="https://www.linkedin.com/in/rocio-belen-picaza-a5996833/" target="_blank">
            <i class="fab fa-linkedin fa-lg"></i>
          </a>
          <a href="https://github.com/ropicaza" target="_blank">
            <i class="fab fa-github fa-lg"></i>
          </a>
        </div>
      </div>
    </div>
  
  </div>

  <h2>Some brands where we collect our data:</h2>

  <div class="cards">
    <a href="https://www.cuspide.com/" target="_blank">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.cuspide.com/images/og_image.png)"></div>
    </a>

    <a href="https://www.tematika.com/" target="_blank">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://bucket3.glanacion.com/Club.LN/anexos/fotos/99/B772799w500.jpg)"></div>
    </a>

    <a href="https://www.bookdepository.com/" target="_blank">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://mma.prnewswire.com/media/1283615/Book_Depository_Logo.jpg?p=facebook)"></div>
    </a>

    <a href="https://www.libreriahernandez.com/" target="_blank">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDIwh33K9eFBHJ8OyINgfT_BUdZjg6mo6qERkZk309khwhGQTzpTVnPG6liYSh1pzsLd4&usqp=CAU)"></div>
    </a>

    <a href="https://libros.mercadolibre.com.ar/libros/" target="_blank">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.prensariotila.com/multimedios/imgs/41976_750.webp)"></div>      
    </a>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.unioncountync.gov/application/files/8315/9432/1864/library-books-for-facebook.jpg);">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h1>BookAdvisor</h1>
        <p>Find your favourite book, just one step from your next reading adventure!</p>
        <%= form_tag books_path, :method => "get" do %>
          <%= text_field_tag :search_online, params[:search_online] %>
          <%= submit_tag "Search", class:"btn-search" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container">

  
  <% if @suggestions[:yenny] != nil %>
    <div class="row justify-content-center">
      <div class="col-md-6 col-lg-12">
        <h4 class="my-4">Most searched at Yenny:</h4>
        <div class="sugerencias-yenny fotos-libros" style="margin-top: 20px;">
          <% @suggestions[:yenny].each do |suggestion| %>
            <a href="<%= suggestion[1]["href"] %>" target="_blank">
              <img src="<%= suggestion[0]["src"] %>" alt="alt" width="145" height="200" class="zoom">
            </a>
          <% end %>
        </div>
      </div>
    </div>
    <hr>
  <% end %>

  <% if @suggestions[:meli] != nil %>
    <div class="row">
      <div class="col-md-6 col-lg-12">
        <h4 class="my-4">Bestselling Books in Mercado Libre</h4>
        <div class="sugerencias-hernandez fotos-libros" style="margin-top: 20px;">
          <% @suggestions[:meli].each do |suggestion| %>
            <a href="<%= suggestion[1] %>" target="_blank">
              <img src="<%= suggestion[0] %>" alt="alt" width="145" height="200" class="zoom">
            </a>
          <% end %>
        </div>
      </div>
    </div>
    <hr>
  <% end %>  
  
  <% if @suggestions[:bookdep] != nil %>
    <div class="row">
      <div class="col-md-6 col-lg-12">
        <h4 class="my-4">Bestselling Books in Book Depository</h4>
        <div class="sugerencias-hernandez fotos-libros" style="margin-top: 20px;">
          <% @suggestions[:bookdep].each do |suggestion| %>
            <a href="<%= suggestion[1] %>" target="_blank">
              <img src="<%= suggestion[0] %>" alt="alt" width="145" height="200" class="zoom">
            </a>
          <% end %>
        </div>
      </div>
    </div>
    <hr>
  <% end %>
    
  <% if @suggestions[:cuspide] != nil %>
    <div class="row">
      <div class="col-md-6 col-lg-12">
        <h4 class="my-4">Bestsellers of the week at Cuspide:</h4>
        <div class="sugerencias-cuspide fotos-libros" style="margin-top: 20px;">
          <% @suggestions[:cuspide].each do |suggestion| %>
            <a href="<%= suggestion[1] %>" target="_blank">
              <img src="<%= suggestion[0] %>" alt="alt" width="145" height="200" class="zoom">
            </a>
          <% end %>
        </div>
      </div>
    </div>
    <hr>
  <% end %>

  <% if @suggestions[:hernandez] != nil %>  
    <div class="row">
      <div class="col-md-6 col-lg-12">
        <h4 class="my-4">Recomended by Librería Hernández:</h4>
        <div class="sugerencias-hernandez fotos-libros" style="margin-top: 20px;">
          <% @suggestions[:hernandez].each do |suggestion| %>
            <a href="<%= suggestion[1] %>" target="_blank">
              <img src="<%= suggestion[0] %>" alt="alt" width="145" height="200" class="zoom">
            </a>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/wishlist.html.erb
<div class="container">
  <div class="mt-3 mb-2">
    <i class="fas fa-arrow-left"> </i>
    <%= link_to "Back to home", root_path %>
  </div>
  <% if @books.count == 0 %>
    <h3 class="my-4">No books yet :(</h3>    
  <% else %>
    <h3 class="my-4">These are your books:</h3>
    <div class="cards-index">
      <div class="row row-cols-1">
        <div class="col mb-4">
          <% @books.each do |book| %>
            <div class="card mb-3">
              <div class="row g-0" style="align-items: center" id="badge">
                <div class="col-lg-4 col-md-4 col-xs-6 text-center">
                  <img src="<%= book[:img_src] %>" alt="book_cover" class="img-card p-1">
                </div>
                <div class="col-lg-8 col-md-8 col-xs-6">
                  <div class="card-body">
                    <h5 class="card-title"><%= book[:title] %></h5>
                    <p class="card-text">
                    <p>Author: <%= book[:author] %></p>
                    <p class="price-item">$<%= book[:price] %></p>
                    <p>Library: <%= book[:library] %></p>
                    <p>Description: <%= book[:description].truncate(140) %> </p>
                    <% if book[:href].present? %>
                      <div class="card-items d-flex">
                          <a href="<%= book[:href] %>" target="_blank"> Buy on <%= book[:library] %></a>
                        <div class="delete-item">
                          <%= link_to wishlist_path(id: book.id), method: :destroy, data: { confirm: "Remove from wishlist? "}, class: "btn-wishlist-delete", style: "align-right" do %>
                            Delete<i class="fas fa-trash-alt pl-2"></i>
                          <% end %>
                        </div>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <hr>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>